.TH minishell 1 "September 2024" "1.0" "User Commands"
.SH NAME
minishell \- the future successor of bash
.SH SYNOPSIS
.B minishell
[OPTION]...
.SH DESCRIPTION
minishell is a not yet fully developed bash successor

.SH OPTIONS
.TP
.B \-h, \-\-help
Displays help information and exits.

.TP
.B \-v, \-\-version
Displays version information and exits.

.SH EXAMPLES
.B myscript \-v
Prints the version of myscript.

.SH AUTHOR
Written by John Doe.

.SH SEE ALSO
.B bash(1).
